### ISSUE TITLE
Travis build errors related to pytest with python 3.5

### ISSUE THREAD

**Issue by vcoder4c** [vcoder4c/cron-validator#4]
https://travis-ci.org/github/vcoder4c/cron-validator/jobs/728867756

**Comment by vcoder4c** [comment]
@dprosperino I noticed after MR #3 , the travis fail with Python 3.5. Could you help to take a look or fix it? Thank you.

**Comment by dprosperino** [comment]
It seems like it loads a wrong pytest version by default. Maybe fixing the version will fix this issue?

**Comment by vcoder4c** [comment]
Fixed by MR #5
